prod:
  only:
    - master
  tags:
    - prod
  stage: deploy
  script:
    - cd /var/www/nuxt-example
    - git pull
    - npm install
    - npm run build
    - cd security
    - npm install
    - sudo chown -R www-data:www-data /var/www/nuxt-example
    - sudo pm2 restart nuxt-example
    - sudo pm2 restart nuxt-example-security
    - sudo pm2 save
